alias ..="cd .."
alias ...="cd ../.."

alias lsa="ls -a" 
alias lsla="ls -la" 
alias home="cd ~"

alias mkdir="mkdir -p" 
alias mv="mv -i" 
alias rm="rm -i"

alias dot="cd ~/.config/"

alias v="nvim"
alias vi="nvim"
alias vim="nvim"

alias temp="/usr/bin/vcgencmd measure_temp"

